volumes:
  ckan_data:
  pg_data:
  solr_data:

services:
  ckan:
    container_name: ckan
    hostname: ckan
    image: 29_ckan:default
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - solr
      - redis
    env_file:
      - path: ./.env-ckan.env
        required: true
      - path: ./.env-ckan.override.env
        required: false
      - path: ./.env-secrets.env
        required: true
    environment:
      - CKAN___BEAKER__SESSION__SECURE=false
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
    ports:
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:5678:5678"
    volumes:
      - ckan_data:/srv/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/action/status_show || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    develop:
      watch:
        - action: sync
          path: /usr/lib/ckan/default/src/ckan/ckan
          target: /srv/app/src/ckan/ckan
        - action: sync
          path: /usr/lib/ckan/default/src/ckan/ckanext
          target: /srv/app/src/ckan/ckanext
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-agsview
          target: /srv/app/src/ckan/ckanext-agsview
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-check-link
          target: /srv/app/src/ckan/ckanext-check-link
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-collection
          target: /srv/app/src/ckan/ckanext-collection
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-contact
          target: /srv/app/src/ckan/ckanext-contact
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-datatablesview_plus
          target: /srv/app/src/ckan/ckanext-datatablesview_plus
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-envvars
          target: /srv/app/src/ckan/ckanext-envvars
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-geoview
          target: /srv/app/src/ckan/ckanext-geoview
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-googleanalytics
          target: /srv/app/src/ckan/ckanext-googleanalytics
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-openapi_viewer
          target: /srv/app/src/ckan/ckanext-openapi_viewer
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-pages
          target: /srv/app/src/ckan/ckanext-pages
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-report
          target: /srv/app/src/ckan/ckanext-report
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-s3filestore
          target: /srv/app/src/ckan/ckanext-s3filestore
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-scheming
          target: /srv/app/src/ckan/ckanext-scheming
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-security
          target: /srv/app/src/ckan/ckanext-security
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-spatial
          target: /srv/app/src/ckan/ckanext-spatial
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-twdh_reports
          target: /srv/app/src/ckan/ckanext-twdh_reports
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-twdh_schema
          target: /srv/app/src/ckan/ckanext-twdh_schema
        - action: sync
          path: /usr/lib/ckan/default/src/ckanext-twdh_theme
          target: /srv/app/src/ckan/ckanext-twdh_theme
        - action: sync
          path: /usr/lib/ckan/default/src/datapusher-plus
          target: /srv/app/src/ckan/datapusher-plus


  db:
    container_name: db
    hostname: db
    build: ./db
    networks:
      - backend
    env_file:
      - ./.env-database.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports: 
      - "9000:5432"

  solr:
    container_name: solr
    hostname: solr
    image: ckan/ckan-solr:2.10-solr9.8-spatial
    networks:
      - backend
    env_file:
      - ./.env-ckan.env
      - ./.env-solr9.env
    volumes:
      - solr_data:/var/solr
      - ./solr9/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/ckan/admin/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports: 
      - "8983:8983"

  redis:
    container_name: redis
    hostname: redis
    env_file:
      - ./.env-redis.env
    image: redis:7.2.0
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports: 
      - "6379:6379"

networks:
  frontend:
  backend:
