version: "3"

volumes:
  ckan_data:
  pg_data:
  solr_data:

services:
  ckan:
    container_name: ckan
    hostname: ckan
    image: 29_ckan:default
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - solr
    env_file:
      - path: ./.env-ckan.env
        required: true
      - path: ./.env-ckan.override.env
        required: false
      - path: ./.env-secrets.env
        required: true
    environment:
      - CKAN___BEAKER__SESSION__SECURE=false
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
    ports:
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:5678:5678"

    volumes:
      - ckan_data:/srv/app/data
    develop:
      watch:
        - action: sync
          path: /usr/lib/ckan/default/src
          target: /srv/app/src/ckan

  db:
    container_name: db
    hostname: db
    build: ./db
    networks:
      - backend
    env_file:
      - ./.env-database.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports: 
      - "9000:5432"
  solr:
    container_name: solr
    hostname: solr
    image: solr:9.8.0
    networks:
      - backend
    env_file:
      - ./.env-ckan.env
      - ./.env-solr9.env
    volumes:
      - solr_data:/var/solr
      - ./solr9/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    hostname: redis
    env_file:
      - ./.env-redis.env
    image: redis:7.2.0
    networks:
      - backend

networks:
  frontend:
  backend:
