CREATE USER ckan WITH ENCRYPTED PASSWORD 'ckan';
ALTER USER ckan WITH SUPERUSER;
CREATE DATABASE ckan WITH OWNER ckan;

CREATE USER datastore WITH ENCRYPTED PASSWORD 'datastore';
ALTER USER datastore WITH SUPERUSER;
CREATE DATABASE datastore WITH OWNER datastore;