name: test-and-push-ecr
run-name: ${{ github.actor }} created a new release
on: [push]
jobs:
  test-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: make --version
      - run: docker compose version
      - run: make build
      - run: docker image ls
