name: test-and-push-ecr
run-name: ${{ github.actor }} created a new release
on: 
  push:
    tags:
      - v*.*.*-*
jobs:
  test-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: aws --version
      - name: aws_config
        run: aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} && aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws configure set default.region us-east-1
      - run: touch ./docker/.env-secrets.env
      - name: aws_s3_key_id
        run: echo CKANEXT__S3FILESTORE__AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> ./docker/.env-secrets.env
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: aws_s3_key
        run: echo CKANEXT__S3FILESTORE__AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} >> ./docker/.env-secrets.env
        env: 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: cat ./docker/.env-secrets.env
      - run: make --version
      - run: docker compose version
      - run: make ecrBuild
      - run: docker image ls
      - run: cd docker && docker compose --file docker-compose_local.yml up -d --wait
      - run: docker compose logs
      - run: docker ps
      - run: curl 0.0.0.0:5000/api/3/status_show
